
// Code generated by stanc v2.29.1
#include <stan/model/model_header.hpp>
namespace model_2_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 28> locations_array__ = 
{" (found before start of program)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 8, column 2 to column 20)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 9, column 2 to column 26)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 13, column 2 to column 23)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 15, column 4 to column 51)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 14, column 17 to line 16, column 3)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 14, column 2 to line 16, column 3)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 28, column 2 to column 18)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 29, column 2 to column 20)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 31, column 4 to column 48)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 32, column 4 to column 39)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 30, column 17 to line 33, column 3)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 30, column 2 to line 33, column 3)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 20, column 2 to column 22)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 21, column 2 to column 21)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 23, column 4 to column 31)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 22, column 17 to line 24, column 3)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 22, column 2 to line 24, column 3)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 2, column 2 to column 8)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 3, column 33 to column 34)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 3, column 2 to column 36)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 4, column 8 to column 9)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 4, column 2 to column 11)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 5, column 8 to column 9)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 5, column 2 to column 11)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 13, column 9 to column 10)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 28, column 9 to column 10)",
 " (in 'D:/Studia/Nowyprojekt_DA/model_2.stan', line 29, column 9 to column 10)"};




class model_2_model final : public model_base_crtp<model_2_model> {

 private:
  int G;
  std::vector<int> N;
  std::vector<int> P;
  std::vector<int> y; 
  
 
 public:
  ~model_2_model() { }
  
  inline std::string model_name() const final { return "model_2_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.1", "stancflags = "};
  }
  
  
  model_2_model(stan::io::var_context& context__,
                unsigned int random_seed__ = 0,
                std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "model_2_model_namespace::model_2_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 18;
      context__.validate_dims("data initialization","G","int",
           std::vector<size_t>{});
      G = std::numeric_limits<int>::min();
      
      
      current_statement__ = 18;
      G = context__.vals_i("G")[(1 - 1)];
      current_statement__ = 19;
      stan::math::validate_non_negative_index("N", "G", G);
      current_statement__ = 20;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{static_cast<size_t>(G)});
      N = std::vector<int>(G, std::numeric_limits<int>::min());
      
      
      current_statement__ = 20;
      N = context__.vals_i("N");
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 20;
      stan::math::check_less_or_equal(function__, "N", N, 365);
      current_statement__ = 21;
      stan::math::validate_non_negative_index("P", "G", G);
      current_statement__ = 22;
      context__.validate_dims("data initialization","P","int",
           std::vector<size_t>{static_cast<size_t>(G)});
      P = std::vector<int>(G, std::numeric_limits<int>::min());
      
      
      current_statement__ = 22;
      P = context__.vals_i("P");
      current_statement__ = 23;
      stan::math::validate_non_negative_index("y", "G", G);
      current_statement__ = 24;
      context__.validate_dims("data initialization","y","int",
           std::vector<size_t>{static_cast<size_t>(G)});
      y = std::vector<int>(G, std::numeric_limits<int>::min());
      
      
      current_statement__ = 24;
      y = context__.vals_i("y");
      current_statement__ = 25;
      stan::math::validate_non_negative_index("theta", "G", G);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("y_sim", "G", G);
      current_statement__ = 27;
      stan::math::validate_non_negative_index("log_lik", "G", G);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 365 + 2;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model_2_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> alpha =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(365, DUMMY_VAR__);
      current_statement__ = 1;
      alpha = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(365);
      Eigen::Matrix<local_scalar_t__, -1, 1> beta =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(2, DUMMY_VAR__);
      current_statement__ = 2;
      beta = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, lp__,
               2);
      std::vector<local_scalar_t__> theta =
         std::vector<local_scalar_t__>(G, DUMMY_VAR__);
      current_statement__ = 6;
      for (int k = 1; k <= G; ++k) {
        current_statement__ = 4;
        stan::model::assign(theta,
          stan::math::inv_logit(
            (stan::model::rvalue(alpha, "alpha",
               stan::model::index_uni(stan::model::rvalue(N, "N",
                                        stan::model::index_uni(k)))) +
              stan::model::rvalue(beta, "beta",
                stan::model::index_uni(stan::model::rvalue(P, "P",
                                         stan::model::index_uni(k)))))),
          "assigning variable theta", stan::model::index_uni(k));
      }
      {
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha, 0, 1));
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, 0, 1));
        current_statement__ = 17;
        for (int k = 1; k <= G; ++k) {
          current_statement__ = 15;
          lp_accum__.add(
            stan::math::bernoulli_lpmf<propto__>(
              stan::model::rvalue(y, "y", stan::model::index_uni(k)),
              stan::model::rvalue(theta, "theta", stan::model::index_uni(k))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model_2_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> alpha =
         Eigen::Matrix<double, -1, 1>::Constant(365,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      alpha = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(365);
      Eigen::Matrix<double, -1, 1> beta =
         Eigen::Matrix<double, -1, 1>::Constant(2,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, lp__,
               2);
      std::vector<double> theta =
         std::vector<double>(G, std::numeric_limits<double>::quiet_NaN());
      out__.write(alpha);
      out__.write(beta);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 6;
      for (int k = 1; k <= G; ++k) {
        current_statement__ = 4;
        stan::model::assign(theta,
          stan::math::inv_logit(
            (stan::model::rvalue(alpha, "alpha",
               stan::model::index_uni(stan::model::rvalue(N, "N",
                                        stan::model::index_uni(k)))) +
              stan::model::rvalue(beta, "beta",
                stan::model::index_uni(stan::model::rvalue(P, "P",
                                         stan::model::index_uni(k)))))),
          "assigning variable theta", stan::model::index_uni(k));
      }
      if (emit_transformed_parameters__) {
        out__.write(theta);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> y_sim =
         Eigen::Matrix<double, -1, 1>::Constant(G,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> log_lik =
         Eigen::Matrix<double, -1, 1>::Constant(G,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 12;
      for (int k = 1; k <= G; ++k) {
        current_statement__ = 9;
        stan::model::assign(log_lik,
          stan::math::bernoulli_lpmf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(k)),
            stan::model::rvalue(theta, "theta", stan::model::index_uni(k))),
          "assigning variable log_lik", stan::model::index_uni(k));
        current_statement__ = 10;
        stan::model::assign(y_sim,
          stan::math::bernoulli_rng(
            stan::model::rvalue(theta, "theta", stan::model::index_uni(k)),
            base_rng__),
          "assigning variable y_sim", stan::model::index_uni(k));
      }
      out__.write(y_sim);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__, -1, 1> alpha =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(365, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= 365; ++sym1__) {
        stan::model::assign(alpha, in__.read<local_scalar_t__>(),
          "assigning variable alpha", stan::model::index_uni(sym1__));
      }
      out__.write(alpha);
      Eigen::Matrix<local_scalar_t__, -1, 1> beta =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(2, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        stan::model::assign(beta, in__.read<local_scalar_t__>(),
          "assigning variable beta", stan::model::index_uni(sym1__));
      }
      out__.write_free_lb(0, beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"alpha", "beta", "theta", "y_sim",
      "log_lik"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(365)
                                                                   },
      std::vector<size_t>{static_cast<size_t>(2)},
      std::vector<size_t>{static_cast<size_t>(G)},
      std::vector<size_t>{static_cast<size_t>(G)},
      std::vector<size_t>{static_cast<size_t>(G)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= 365; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_sim" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= 365; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_sim" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= G; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(365) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(G) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"y_sim\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(365) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(G) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"y_sim\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(G) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (365 + 2);
      const size_t num_transformed = G;
      const size_t num_gen_quantities = 
  (G + G);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (365 + 2);
      const size_t num_transformed = G;
      const size_t num_gen_quantities = 
  (G + G);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 2> names__{"alpha", "beta"};
      const std::array<Eigen::Index, 2> constrain_param_sizes__{365, 2};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = model_2_model_namespace::model_2_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return model_2_model_namespace::profiles__;
}

#endif


